
language: node_js
sudo: false
node_js:
  - "stable"

script: npm run deploy

before_install:
  # Connect Chromium to run tests in Travis
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

deploy:
  edge:
    branch: v1.8.47
  local-dir: build
  provider: pages
  fqdn: favioli.com
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
branch: master
